Upgrade ios project, android manifest, svg package
Softeq/Kudos pull request #201
Opened 2020-09-09 12:34 UTC by wcoder

2020-09-09 12:39 UTC, SavikPavel approved these changes

2020-09-16 08:11 UTC, vadimpylsky requested changes

2020-09-16 08:11 UTC, vadimpylsky commented on src/android/app/src/main/AndroidManifest.xml
>          android:allowBackup="false"
Please double check android target version

2020-09-16 15:39 UTC, wcoder commented on src/android/app/src/main/AndroidManifest.xml
>          android:allowBackup="false"
Versions raised

2020-09-16 15:43 UTC, merged