mandatory update screen
Softeq/Kudos pull request #227
Opened 2020-11-13 12:53 UTC by vadimpylsky

2020-11-13 14:44 UTC, wcoder requested changes

2020-11-13 14:44 UTC, wcoder commented on src/lib/services/auth_service.dart
> +    return true;
Please revert check

2020-11-13 14:44 UTC, wcoder commented on src/lib/viewmodels/auth_viewmodel.dart
> +
Rudimental import

2020-11-13 14:44 UTC, wcoder commented on src/lib/pages/mandatory_update_page.dart
> +                textAlign: TextAlign.center,
Optional: maybe add a button to open the appcener?

2020-11-13 14:44 UTC, wcoder commented on src/lib/kudos_app.dart
> +        locator<MandatoryUpdateDatabaseService>().refreshSubscriptions();
Can be better to move in `HomeViewModel`

2020-11-16 19:17 UTC, vadimpylsky commented on src/lib/viewmodels/auth_viewmodel.dart
> +
resolved

2020-11-16 19:18 UTC, vadimpylsky commented on src/lib/services/auth_service.dart
> +    return true;
resolved

2020-11-17 10:07 UTC, wcoder approved these changes

2020-11-17 11:41 UTC, wcoder approved these changes

2020-11-19 08:05 UTC, merged